#ifndef ENUMS
#define ENUMS

enum rules {
  nativeType = 500,
  variableName,
  variableBinding,
  variableDeclarationList,
  variableDeclaration,
  optionalVariableType,
  variableInitialization,
  variableKind,
  value,
  mathValue,
  expr,
  expression,
  sourceElements,
  sourceElement,
  statement,
  program,
  objectInitializer,
  newObject,
  arrayAccessor,
  functionCall,
  ternaryExpression,
  block , 
  importStatement ,
  functionStatement ,
  forStatement,
  ifStatement ,
  whileStatement ,
  continueStatement ,
  breakStatement,
  withStatement ,
  throwStatement ,
  tryStatement ,
  iterationStatement,
  superStatement,
  classStatement,
  packageStatement,
  returnStatement,
  assignStatement,
  getterSetter,
  valueList,
  as,
  functionDeclaration,
  logicalOperator,
  accessValue,
  optionalForIncrement,
  assign,
  functionHeader,
  elseStatement,
  prefixKeyword,
  suffixKeyword,
  modifier,
  modifierPrefix,
  modifierSuffix,
  optionalForConditional,
  finally,
  catch,
};

#endif
